server:
  port: 9030
  servlet:
    context-path: /shipping

spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shippingDB
    username: postgres
    password: POSTGRESPASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
