server:
  port: 9040
  servlet:
    context-path: /shipping

spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:postgresql://localhost:5432/usersDB
    username: postgres
    password: POSTGRESPASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
