spring:
  application:
    name: discovery-Service

server:
  port: 8761
  #address: 192.168.1.16

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost


